apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: sample-ratelimit-plugin     # Must match name in Ingress annotation
 namespace: api-demo
 annotations:
  kubernetes.io/ingress.class: kong
config:
 minute: 5    # Number of requests allowed per minute
 limit_by: consumer
 policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: sample-api-key-plugin          # Must match name in Ingress annotation
 namespace: api-demo
 annotations:
  kubernetes.io/ingress.class: kong
config:
 key_names:
   - apikey                        # Header name for the API key
 hide_credentials: true
plugin: key-auth