apiVersion: v1
kind: Secret
metadata:
 name: api-demo-secret                # Must match name referenced in KongConsumer
 namespace: api-demo
 labels:
   konghq.com/credential: key-auth
type: Opaque
stringData:
 kongCredType: key-auth
 key: 1PK5pXCbFRYFcE016M9LkWnqftuqpNxW1mCJlNkleDzQZMVKlUyrgLIN1ej2rfh1              # Your chosen API key value